### ISSUE TITLE
highlight.sector(sector.index = sector, col = colour): colour vector of same length as sector 

### ISSUE THREAD

**Issue by tnaake** [jokergoo/circlize#11]
Hi,
I am using currently `circlize::highlight.sector()`. I was wondering if it's possible to change the function as such as to give to the function `highlight.sector` a vector `colour` which has the same length as `sector`, in order to highlight sectors in different colours? 

E.g. I want to highlight the sectors "a", "b", "c" then 

`highlight.sector(sector.index = c("a", "b", "c"), col =c("blue", "red", "green"))` will highlight the sectors in the corresponding colour.

**Comment by jokergoo** [comment]
Hi, thanks for your advice! 

Currently I don't have the plan to make `col` option vectorized. The reason is that if `col` is vectorized, all other options should also be considered to be vectorized. For some of the options (e.g. `lwd`, `lty`), there is no problem. But for `padding` and `...` which is passed to `circos.text`, that would be a problem.
