### ISSUE TITLE
Track gridlines across all sectors?

### ISSUE THREAD

**Issue by ripkrizbi** [jokergoo/circlize#122]
Hi, 

I'm trying to make the gridlines in a histogram track, to go around the entire track (a kind of extended ticks from a y-axis, similar to what the original circos has). I was not able to find a way to get this working -  if I leave the gap between sectors, my grid lines have an ugly break, but I need to have sector spacing in order to separate my datapoints.

What would be the best way to go about solving this problem?

**Comment by jokergoo** [comment]
You can go to these tracks and add lines by `circos.lines()`:

```r
set.seed(123)
x = rnorm(1600)
factors = sample(letters[1:16], 1600, replace = TRUE)
circos.initialize(factors = factors, x = x)
circos.trackHist(factors = factors, x = x, col = "#999999", 
	border = "#999999")
for(sn in get.all.sector.index()) {
	set.current.cell(sector.index = sn, track.index = get.current.track.index())
	breaks = seq(0, CELL_META$ylim[2], by = 10)
	for(b in breaks) {
		circos.lines(CELL_META$cell.xlim, rep(b, 2), lty = 3, col = "#00000040")
	}
}
```

![image](https://user-images.githubusercontent.com/449218/60581334-e5e9e400-9d86-11e9-9b5f-dc482a99c469.png)

You can see the ylim for cells in the first track by `circos.info(track.index = 1)`.

**Comment by ripkrizbi** [comment]
Thanks, but I'm trying to find a way to avoid interruptions between sectors - to have continuous lines without sector breaks.

**Comment by jokergoo** [comment]
Then you need to define a function which draws the circle, such as following:

```r
draw_circle = function(r, ...) {
	d = seq(0, 2*pi, length = 360)
	x = cos(d)*r
	y = sin(d)*r
	lines(x, y, ...)
}
```

And after you draw the histogram track,

```r
set.seed(123)
x = rnorm(1600)
factors = sample(letters[1:16], 1600, replace = TRUE)
circos.initialize(factors = factors, x = x)
circos.trackHist(factors = factors, x = x, col = "#999999", 
	border = "#999999")
```

you can calculate the radius of the circle you want to add. Here `CELL_META` correspond to the last cell you added and `circlize()` is applied to the last cell. Since here we only want the radius, we only need to make sure it is applied in the last track which is the last created track.

```r
breaks = seq(0, CELL_META$ylim[2], by = 10)
radius = circlize(x = 0, y = breaks)[, 2] # value of `x` is not important here

for(r in radius) {
	draw_circle(r, lty = 3, col = "red")
}
```

![image](https://user-images.githubusercontent.com/449218/60743364-90bdf600-9f71-11e9-9d4c-686d3b1fd1e7.png)
