### ISSUE TITLE
nested zooming with genomicDensity function

### ISSUE THREAD

**Issue by alessandrotestori** [jokergoo/circlize#245]
Hello!
 I would like to zoom two bed files (from ChIPseq experiments) that I represented through the circos.genomicDensity function.
Since I did not manage to use the circos.genomicDensity function in a nested zooming, I tried to represent a bed file (toy data from the example at https://jokergoo.github.io/circlize_book/book/nested-zooming.html#basic-idea) with the circos.lines function (code below). Is this the way I can do it? If this is the case, how can I use circos.genomicInitialize and circos.genomicTrack instead of circos.initialize and circos.track in the f1 and f2 functions? - thanks a lot for the circlize package!

```r
## code starts here

library(circlize)
library(dplyr)

#from https://jokergoo.github.io/circlize_book/book/nested-zooming.html#basic-idea

set.seed(123)
df = data.frame(cate = sample(letters[1:8], 400, replace = TRUE),
                x = runif(400),
                y = runif(400),
                stringsAsFactors = FALSE)
df = df[order(df[[1]], df[[2]]), ]

rownames(df) = NULL
df$interval_x = as.character(cut(df$x, c(0, 0.2, 0.4, 0.6, 0.8, 1.0)))
df$name = paste(df$cate, df$interval_x, sep = ":")
df$start = as.numeric(gsub("^\\((\\d(\\.\\d)?).*(\\d(\\.\\d)?)]", "\\1", df$interval_x))
df$end = as.numeric(gsub("^\\((\\d(\\.\\d)?),(\\d(\\.\\d)?)]$", "\\3", df$interval_x))

#I need to represent 2 bed files
#I am going to add the end column to df, that I am going to name "z", in case it is required to represent genomic regions;
#I also need to add a second value besides y (I name it "w") because I want to represent a two ChIPseq tracks

a <- df[[2]]
b <- a[-1]
c <- append(b,1)

df <- data.frame(cate=df[[1]], x=df[[2]], z=c, y=df[[3]], w=df[[3]], interval_x=df[[4]], name=df[[5]], start=df[[6]], end=df[[7]])

#end
#from https://jokergoo.github.io/circlize_book/book/nested-zooming.html#basic-idea

nm = sample(unique(df$name), 20)

df2 = df[df$name %in% nm, ]

correspondance = unique(df2[, c("cate", "start", "end", "name", "start", "end")])
zoom_sector = unique(df2[, c("name", "start", "end", "cate")])

zoom_data = df2[, c("name", "x", "z", "y", "w")] #name, x, z, y, and w variables

data = df[, 1:5]
sector = data.frame(cate = letters[1:8], start = 0, end = 1, stringsAsFactors = FALSE)

sector_col = structure(rand_color(8, transparency = 0.5), names = letters[1:8])


#from https://jokergoo.github.io/circlize_book/book/nested-zooming.html#basic-idea
#using circos.lines instead of circos points as a surrogate for circos.genomicDensity()
#and zooming 2 tracks

f1 = function() {
    circos.par(gap.degree = 10)
    circos.initialize(sector[, 1], xlim = sector[, 2:3])
    circos.track(data[[1]], x = data[[2]], y = data[[4]], ylim = c(0, 1), 
        panel.fun = function(x, y) {
            circos.lines(x, y, area=TRUE, col = "red")
    })
	circos.track(data[[1]], x = data[[2]], y = data[[5]], ylim = c(0, 1), 
        panel.fun = function(x, y) {
            circos.lines(x, y, area=TRUE, col = "blue")
    })
}

f2 = function() {
    circos.par(gap.degree = 2, cell.padding = c(0, 0, 0, 0))
    circos.initialize(zoom_sector[[1]], xlim = as.matrix(zoom_sector[, 2:3]))
    circos.track(zoom_data[[1]], x = zoom_data[[2]], y = zoom_data[[4]], 
        panel.fun = function(x, y) {
            circos.lines(x, y, area=TRUE, col="red")
    })
	circos.track(zoom_data[[1]], x = zoom_data[[2]], y = zoom_data[[5]], 
        panel.fun = function(x, y) {
            circos.lines(x, y, area=TRUE, col="blue")
    })
}
circos.nested(f2, f1, correspondance[, c(4:6, 1:3)])
```

**Comment by jokergoo** [comment]
Have you checked this link https://jokergoo.github.io/circlize_book/book/nested-zooming.html#visualization-of-dmrs-from-tagmentation-based-wgbs which also associates two lists of genomic regions? I think the key thing is for the "zoomed" data, you need to reformat the chromosome name. If each chromosome only has one region zoomed, then you don't need to do anything. If some chromosomes have multiple regions that need to be zoomed, then for the second set of regions, the chromosome name need to be reformatted as, e.g. `chr1_1`, `chr1_2`, ... because each zoomed region will be as different sectors in the zoomed circle and they must have different names.

`f1()` and `f2()` are just normal code for making circular plots. You can just put `circos.genomicInitialize()` and `circos.genomicTrack()` as in the normal way. When you separatedly execute `f1()` or `f2()`, they should produce normal circular plots. And the two circular plots by `f1()` and `f2()` are automatically arranged according to the value in `correspondance`. So you just take care of how `correspondance` is constructed.
