### ISSUE TITLE
Slow/doesn't finish with larger datasets?

### ISSUE THREAD

**Issue by wkc1986** [jokergoo/circlize#248]
I'm trying to plot 4 sets of 1000000 methylation loci each in an R notebook, and the plotting runs for days without finishing. Here's a simplified version of my code:

```r
}
circos.initializeWithIdeogram(species = "mm10")
mapply(function(bed) {
  circos.genomicTrackPlotRegion(
    bed,  
    panel.fun = function(region, value, ...) { 
      circos.genomicLines( 
        region = region, 
        value = value, 
        numeric.column = "meanMeth", 
        type = "s",
        )
    },
    track.height = 0.1)
  }, bed = ssample, SIMPLIFY = FALSE)
  circos.clear()
}
```

Where `ssample` is a list of 4 `data.tables` each having 1000000 rows. Am I doing something wrong?

**Comment by jokergoo** [comment]
It is not a good idea of directly plotting all 4x1M data points. You won't see the detail of every single point. On the other hand,  since you draw lines, in circlize, lines are actually not direct, which means they are curves and each curve is represented by a list of points, which makes the number of points to draw even higher.

I would suggest to down sample to e.g. 2000 or you need to change another way to visualize your data.
