### ISSUE TITLE
draw.sector Display is not round

### ISSUE THREAD

**Issue by wdb-web** [jokergoo/circlize#249]
![image](https://user-images.githubusercontent.com/53480488/110809510-e9ee3900-82bf-11eb-95c2-9058d2f5f5bf.png)

I will use draw.sector to draw a new plot but The circular figure drawn is not round
    draw.sector(0,360*as.numeric(data$n.AC)/as.numeric(data$sum),
                center = c(
                    cos((get.cell.meta.data("cell.start.degree", sector.index = name[3])-
                             (i-1)*(360/21/2.69/2.44)-k)*2*pi/360),
                    sin((get.cell.meta.data("cell.start.degree", sector.index = name[3])- 
                             (i-1)*(360/21/2.69/2.44)-k)*2*pi/360)),
                rou1 = 0.02, clock.wise = FALSE,border = colT[2], col = colT[2],
                lwd = 2, lty = 2)

**Comment by wdb-web** [comment]
The circular graph drawn by draw.sector is not round and more like a polygon

**Comment by jokergoo** [comment]
Err.. How do you think it is not round?

**Comment by wdb-web** [comment]
![image](https://user-images.githubusercontent.com/53480488/112162599-28bcb100-8c27-11eb-8c15-d669148da9dd.png)

**Comment by wdb-web** [comment]
When there are multiple groups, non-circular graphs will appear

**Comment by jokergoo** [comment]
In circlize, circles or arcs are draw by a list of straight segments to simulate smooth curves and the number of segments is controlled by `circos.par("unit.circle.segments")` parameter. With higher value, the better approximation but with higher file size. The default value works well for large circles, but maybe you need to increase it for very small circles.

See following experiment:

```r
par(mfrow = c(1, 2))

plot(c(-1, 1), c(-1, 1), type = "n", axes = FALSE, ann = FALSE, asp = 1)

for(r in c(0.02, 0.05, 0.1, 0.2, 0.5, 1)) {
	draw.sector(0, 360, r)
}

circos.par(unit.circle.segments = 2000)

plot(c(-1, 1), c(-1, 1), type = "n", axes = FALSE, ann = FALSE, asp = 1)

for(r in c(0.02, 0.05, 0.1, 0.2, 0.5, 1)) {
	draw.sector(0, 360, r)
}

circos.par(RESET = TRUE)
```

For the most inside circle (radius = 0.02), the default approximation is not perfect (the left plot) while when increase the value of `unit.circle.segments`, the approximation gets better (the right plot):

<img src="https://user-images.githubusercontent.com/449218/112450682-ed200500-8d54-11eb-94a8-944a5927d7fa.png" width="40%"><img src="https://user-images.githubusercontent.com/449218/112450690-ee513200-8d54-11eb-98a1-0554102d5ca0.png" width="40%">

So to solve your problem, if you generate the plot as a png file, you can put

```r
circos.par(unit.circle.segments = 2000) # may be a higher value
```

at the beginning of your code.

Or if you generate the plot as a PDF file, you can just put `circos.par(unit.circle.segments = ...)` only before where you use `draw.sector(...)` and reset it after your pie is drawn, so that this change only affects your pie charts:

```r
...
circos.par(unit.circle.segments = 2000) # may be a higher value
draw.sector(...)
circos.par(unit.circle.segments = 500) # this is the default
...
```

**Comment by wdb-web** [comment]
Thank you, teacher. I also want to ask if there is a function to make a pie chart directly. Although this method can be used to add a pie chart a little bit, it is really troublesome.

**Comment by jokergoo** [comment]
I can not write a full functional function for you, but I can provide you one with basic functionality:

```r

piechart = function(x, center = c(0, 0), r = 1, col = "white", border = "black") {
	n = length(x)
	if(length(col) == 1) col = rep(col, n)

	x = x/sum(x)
	d = cumsum(c(0, x*360))
	for(i in seq_along(d)[-1]) {
		draw.sector(d[i], d[i-1], r, center = center, col = col[i-1], border = border)
	}
}

plot(c(-1, 1), c(-1, 1))
piechart(runif(5), col = 2:6)
piechart(runif(5), center = c(-0.5, 0.5), r = 0.5, col = 2:6)
piechart(runif(5), center = c(0.5, -0.5), r = 0.2, col = 2:6)
```

![image](https://user-images.githubusercontent.com/449218/112531957-8298b480-8da8-11eb-892d-354cf29ca319.png)
