### ISSUE TITLE
Error in circos.initialize(factors = factor(cate, levels = cate), xlim = cbind(rep(0,  : 

### ISSUE THREAD

**Issue by eudoraleer** [jokergoo/circlize#35]
I have encountered the following error while using chordDiagram:

**Error in circos.initialize(factors = factor(cate, levels = cate), xlim = cbind(rep(0,  : 
  Range of the sector (IGHV4.59   ) cannot be 0.**

What exactly is the problem? How can this be fixed?

Thanks!

Best Regards,
Lu

**Comment by jokergoo** [comment]
Hi,

This means for the category "IGHV4.59", the data range is 0.

Can you also attach the complete code here?

**Comment by jokergoo** [comment]
Hi, today another user reported the same bug as yours. After digging into the code, I found the problem and have fixed it.

In chord diagram, by default, tiny sectors are removed by `reduce` argument because they are too small that they cannot be read or distinguished in the chord diagram. If the input is a matrix `M`, the 
rows and columns are filtered to have a sub-matrix `M2`. The problem was, in `M2`, it is still possible that row sums or column sums in `M2` are zero, which results in the error you had.

You can update the package from GitHub:

```r
library(devtools)
install_github("jokergoo/circlize")
```
