### ISSUE TITLE
small sector value should perhaps be the largest value

### ISSUE THREAD

**Issue by pank** [jokergoo/circlize#6]
Hi,

When there are many small sectors, perhaps it would make sense to use the last value of its arc rather than zero.  Consider this picture

![many zeros](http://i.imgur.com/ZVdpV9H.png)

It is clear that it starts from zero (from the context), but it would be nicer to see the total value, as is shown by default on larger arces.  So for the larger red arc, it would show something like 110 or whatever is the numerical value.

BTW: Sorry if my terminology is off.  I hope it's clear none the less.

Another thing is the overplotting of labels.  I guess this is an issue that cannot be solved automatically, as it depends on the "width" of labels.

Thanks,
Rasmus

**Comment by jokergoo** [comment]
Yes, you are right. This is the default style of the function. Actually, for the tiny sectors, add the none-zero numbers can not help too much because same as the sector labels, the numbers will also overlap with each other. On the other hand, the range for the tiny sectors actually can be inferred by neighbouring large sectors.

When I apply `chordDiagram()` to real data where there are tiny sectors, I always first draw the chord diagram
without adding sector names and axes, later I add the names and axes only if the width of the sector is larger than some cutoff (the width of the sector can be easily get by `get.cell.meta.data()`.

In following example, sectors with less than 10 degrees are with neither names nor axes

```{r}

mat = matrix(runif(36), 6, 6)
mat[1,1] = 40
rownames(mat) = letters[1:6]
colnames(mat) = LETTERS[1:6]
chordDiagram(mat, annotationTrack = "grid",
	preAllocateTracks = list(track.height = 0.1))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
	xlim = get.cell.meta.data("xlim")
	xplot = get.cell.meta.data("xplot")
	ylim = get.cell.meta.data("ylim")
	sector.name = get.cell.meta.data("sector.index")
	if(abs(xplot[2] - xplot[1]) > 10) {
		circos.text(mean(xlim), mean(ylim), sector.name, facing = "inside",
		niceFacing = TRUE, adj = c(0.5, 0))
		circos.axis("bottom", labels.cex = 0.4)
	}
}, bg.border = NA)
```

**Comment by pank** [comment]
Zuguang Gu <notifications@github.com> writes:

> Yes, you are right. This is the default style of the function. Actually, for the tiny sectors, add the none-zero numbers can not help too much because same as the sector labels, the numbers will also overlap with each other. On the other hand, the range for the tiny sectors actually can be inferred by neighbouring large sectors.

Indeed. 

> When I apply `chordDiagram()` to real data where there are tiny sectors, I always first draw the chord diagram
> without adding sector names and axes, later I add the names and axes only if the width of the sector is larger than some cutoff (the width of the sector can be easily get by `get.cell.meta.data()`.

This is indeed what I ended up doing.  There's even examples in the
vignette that one can extrapolate from.

Thanks,
Rasmus

-- 
Evidence suggests Snowden used a powerful tool called monospaced fonts
