### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by abhisheksinghnl** [jokergoo/circlize#70]
Hi, 

I am working with the library circlize, it works very well for all my data except for this dataset:

```
chr16 26222939 26223104
chr20  2270091  2270356
```

It has only two points that needs to be plotted.

What I am doing is:

```
 library(circlize)
 circos.initializeWithIdeogram(plotType = c("axis", "labels"))
 bed1=read.table("DSG_FA_ONLY_FA.E1.ER.bed", header=F, sep="\t")
 bed_list = list(bed1)
 circos.genomicRainfall(bed_list, pch = 16, cex = 0.4, col = c("blue")) # no errors till here
circos.genomicDensity(bed_list[[1]], col = c("blue"), track.height = 0.1)
Error in circos.createPlotRegion(track.start = track.start, track.height = track.height,  : 
  range of `ylim` should be different.
```

Could you please help in fixing this error. 

Thank you in advance.

**Comment by jokergoo** [comment]
Hi, it is because the current version, `genomicDensity()` function only calculates to the maximum position in each chromosome and if in the last window less than 50% of it covers to the input region (which is `c(1, max(pos))`), it will be removed (so actually there is no data for chr20 in your data).

Now I have updated the package to allow `genomicDensity()` to calculate to the full length of the chromosome. Please update it by:

```{r}
devtools::install_github("jokergoo/circlize")
```

**Comment by abhisheksinghnl** [comment]
Hi,

Thank you for explanation and updating the package.

Best
Abhishek
