### ISSUE TITLE
Limit in # of sectors?

### ISSUE THREAD

**Issue by golharam** [jokergoo/circlize#76]
I'm trying to initialize circlize with about 800 sectors but get this data (subjectids is a Factor with 807 levels):

circos.initialize(subjectids, xlim = c(0,1))

Error in stop_wrap("Maybe your `gap.degree` is too large so that there is no space to allocate sectors.") : Maybe your `gap.degree` is too large so that there is no space to allocate sectors.

Is there a limit to how many sectors I have?   How do I then display a large # of subjects (patients) as their own individual sectors?

**Comment by golharam** [comment]
circos has this restriction too, but can be overridden.   If I have to display that many sectors, then I should rethink what I want to display.

**Comment by jokergoo** [comment]
By default there is 1 degree gap between two neighbouring sectors. If you set `circos.par(gap.degree = 0)`, the error might disappear. 

From the other hand, I believe it is not a good idea to directly put 800 sectors because you won't see anything. Maybe you can group all your 807 levels into several subgroups?
