### ISSUE TITLE
Animation support/Transition

### ISSUE THREAD

**Issue by pank** [jokergoo/circlize#8]
Hi,

I have a network for which I produce a `circelize` graph every month.  It turns out that there are a lot of variations over months.  I would now like to make an animation of the network over time. 

I was wondering if it is possible to calculate or produce 'intermediary' networks that would make transistions from month `t-1` to `t` smooth?  In other  words I want to replicate the `transition()` function of `d3.js`.  The two things that would be most helpful to animate are:

- changes in the relative size of nodes
- changes in edges

I don't mind a fixed order for nodes.

I don't relly understand the internal data representation of `circlize`, so I'm not sure what is the best way to tackle this.

Thanks,
Rasmus

**Comment by jokergoo** [comment]
I think it would be difficult to do this by circlize because circlize is designed for static plots. But if you can generate the adjacent matrix or the adjacent list which corresponds to the smoothing between two states, then you can generate a png for each step and finally merging them to construct an animated gif:

If following code, `mat1` corresponds to state `t` and `mat2` corresponds to state `t+1`:

```{r}
set.seed(123)
mat1 = matrix(sample(9, 9), 3)
mat2 = matrix(sample(9, 9), 3)

png()
chordDiagram(mat1, grid.col = 1:6)
for(i in 1:9) {
    m = mat1 + (mat2 - mat1)*i/10
    chordDiagram(m, grid.col = 1:6)
}
chordDiagram(mat2, grid.col = 1:6)
dev.off()

system("convert -delay 10 Rplot*.png test.gif")
```

And the animation is:
![test](https://cloud.githubusercontent.com/assets/449218/10367183/50af5b6c-6dcf-11e5-9fab-10b9321753c6.gif)

**Comment by talgalili** [comment]
p.s.: the animation package may also be helpful
https://cran.r-project.org/web/packages/animation/index.html
